server {
    listen 80;
    server_name test.dyna.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name test.dyna.com;

    ssl_certificate     /etc/nginx/certs/test.dyna.com.crt;
    ssl_certificate_key /etc/nginx/certs/test.dyna.com.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /var/www/html/pub;
    index index.php;
    fastcgi_buffers 16 16k;
    fastcgi_buffer_size 32k;
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    
    resolver 127.0.0.11 valid=30s;
    location ~ ^/.+\.php(/|$) {
        fastcgi_pass php-fpm:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS on;
        include fastcgi_params;
    }

    location /pma/ {
        auth_basic "Restricted Access";
        auth_basic_user_file /etc/nginx/.htpasswd;
        proxy_pass http://phpmyadmin:80/;
        proxy_set_header Host $host;
    }
}
